{{- $envVars := include "impress.backend.celery.env" (list . .Values.backend) -}}
{{- $fullName := include "impress.celery.worker.fullname" . -}}
{{- $component := "celery-worker" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- with .Values.backend.dpAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "impress.common.labels" (list . $component) | nindent 4 }}
spec:
  replicas: {{ .Values.backend.celery.replicas }}
  selector:
    matchLabels:
      {{- include "impress.common.selectorLabels" (list . $component) | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.backend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "impress.common.selectorLabels" (list . $component) | nindent 8 }}
    spec:
      {{- if $.Values.image.credentials }}
      imagePullSecrets:
        - name: {{ include "impress.secret.dockerconfigjson.name" (dict "fullname" (include "impress.fullname" .) "imageCredentials" $.Values.image.credentials) }}
      {{- end}}
      {{- if .Values.backend.serviceAccountName }}
      serviceAccountName: {{ .Values.backend.serviceAccountName }}
      {{- end }}
      shareProcessNamespace: {{ .Values.backend.shareProcessNamespace }}
      containers:
        {{- with .Values.backend.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: {{ .Chart.Name }}
          image: "{{ (.Values.backend.image | default dict).repository | default .Values.image.repository }}:{{ (.Values.backend.image | default dict).tag | default .Values.image.tag }}"
          imagePullPolicy: {{ (.Values.backend.image | default dict).pullPolicy | default .Values.image.pullPolicy }}
          {{- with .Values.backend.celery.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.celery.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or $envVars .Values.jwtKeys.enabled }}
          env:
            {{- $envVars | indent 12 }}
            {{- if .Values.jwtKeys.enabled }}
            {{- include "impress.jwtKeys.backendEnv" . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- $envFrom := concat (.Values.backend.envFrom | default list) (.Values.backend.celery.envFrom | default list) }}
          {{- if $envFrom }}
          envFrom:
            {{- toYaml $envFrom | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          {{- if .Values.backend.celery.probes.liveness }}
          livenessProbe:
            {{- include "impress.probes.abstract" (merge .Values.backend.celery.probes.liveness (dict "targetPort" .Values.backend.service.targetPort )) | nindent 12 }}
          {{- end }}
          {{- if .Values.backend.celery.probes.readiness }}
          readinessProbe:
            {{- include "impress.probes.abstract" (merge .Values.backend.celery.probes.readiness (dict "targetPort" .Values.backend.service.targetPort )) | nindent 12 }}
          {{- end }}
          {{- if .Values.backend.celery.probes.startup }}
          startupProbe:
            {{- include "impress.probes.abstract" (merge .Values.backend.celery.probes.startup (dict "targetPort" .Values.backend.service.targetPort )) | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.celery.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.jwtKeys.enabled }}
            {{- include "impress.jwtKeys.volumeMount" . | nindent 12 }}
            {{- end }}
            {{- range $index, $value := .Values.mountFiles }}
            - name: "files-{{ $index }}"
              mountPath: {{ $value.path }}
              subPath: content
            {{- end }}
            {{- range $name, $volume := .Values.backend.persistence }}
            - name: "{{ $name }}"
              mountPath: "{{ $volume.mountPath }}"
            {{- end }}
            {{- range .Values.backend.extraVolumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath | default "" }}
              readOnly: {{ .readOnly }}
            {{- end }}
            {{- if .Values.backend.themeCustomization.enabled }}
            - name: theme-customization
              mountPath: {{ .Values.backend.themeCustomization.mount_path }}
              readOnly: true
            {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.jwtKeys.enabled }}
        {{- include "impress.jwtKeys.volume" . | nindent 8 }}
        {{- end }}
        {{- range $index, $value := .Values.mountFiles }}
        - name: "files-{{ $index }}"
          configMap:
            name: "{{ include "impress.fullname" $ }}-files-{{ $index }}"
        {{- end }}
        {{- range $name, $volume := .Values.backend.persistence }}
        - name: "{{ $name }}"
          {{- if eq $volume.type "emptyDir" }}
          emptyDir: {}
          {{- else }}
          persistentVolumeClaim:
            claimName: "{{ $fullName }}-{{ $name }}"
          {{- end }}
        {{- end }}
        {{- if .Values.backend.themeCustomization.enabled }}
        - name: theme-customization
          configMap:
            name: docs-theme-customization
        {{- end }}
        {{- range .Values.backend.extraVolumes }}
        - name: {{ .name }}
          {{- if .existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .existingClaim }}
          {{- else if .secret }}
          secret:
            {{ toYaml .secret | nindent 12 }}
          {{- else if .hostPath }}
          hostPath:
            {{ toYaml .hostPath | nindent 12 }}
          {{- else if .csi }}
          csi:
            {{- toYaml .csi | nindent 12 }}
          {{- else if .configMap }}
          configMap:
            {{- toYaml .configMap | nindent 12 }}
          {{- else if .emptyDir }}
          emptyDir:
            {{- toYaml .emptyDir | nindent 12 }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
