{{- with .Values.user }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ .username }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
  password: {{ .password | quote }}
---
apiVersion: valkey.buf.red/v1alpha1
kind: User
metadata:
  name: {{ $.Release.Name }}-{{ .username }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    # see valkey.yaml
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  accountType: custom
  arch: failover
  instanceName: {{ $.Release.Name }}
  username: {{ .username | quote }}
  passwordSecrets:
    - {{ $.Release.Name }}-{{ .username }}
  aclRules: {{ .aclRules | quote }}
{{- end }}
