# Generated by Django 5.2.14 on 2026-08-10 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_document_document_attachments_gin"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentMigration",
            fields=[
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="migration",
                        serialize=False,
                        to="core.document",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Migrated"),
                            ("already", "Already migrated"),
                            ("empty", "Nothing in the object storage"),
                            ("nothing", "No readable version"),
                            ("failed", "Failed"),
                        ],
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "versions",
                    models.PositiveIntegerField(default=0, verbose_name="versions"),
                ),
                (
                    "applied",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="versions that added content, one activity entry each",
                        verbose_name="applied",
                    ),
                ),
                (
                    "skipped",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="versions that could not be read",
                        verbose_name="skipped",
                    ),
                ),
                (
                    "dropped",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="versions older than the ones the server replays",
                        verbose_name="dropped",
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(default=0, verbose_name="duration"),
                ),
                (
                    "error",
                    models.TextField(blank=True, default="", verbose_name="error"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated on"),
                ),
            ],
            options={
                "verbose_name": "Document migration",
                "verbose_name_plural": "Document migrations",
                "db_table": "impress_document_migration",
                "indexes": [
                    models.Index(
                        fields=["status"], name="impress_doc_status_7d8208_idx"
                    )
                ],
            },
        ),
    ]
